export const newsData = [
    {
      id: 'covid-update',
      title: 'Important COVID-19 Visiting Update - Cardiff & Barry Homes',
      excerpt: 'Due to the increase in Coronavirus confirmed cases throughout Wales and Cardiff area, we are suspending all pod visits in our Cardiff & Barry Nursing Homes until further review.',
      image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      category: 'health',
      date: 'Dec 21, 2020',
      location: 'Cardiff & Barry',
      author: 'Bellavista Management',
      badge: '🚨 Important Update',
      views: 5247,
      likes: 89,
      shares: 156,
      comments: 23,
      readTime: '5 min read'
    },
    {
      id: 'christmas-event',
      title: 'Christmas Celebration Week',
      excerpt: 'Join us for a magical week of festive activities, carol singing, and special holiday meals across all our homes.',
      image: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
      category: 'events',
      date: 'Dec 20-27, 2024',
      location: 'All Locations',
      author: 'Events Team',
      badge: '',
      views: 1247,
      likes: 45,
      shares: 23,
      comments: 12,
      readTime: '2 min read'
    },
    {
      id: 'excellence-award',
      title: 'Excellence in Care Award 2024',
      excerpt: 'Barry Seaside home receives prestigious recognition for outstanding dementia care and family support services.',
      image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
      category: 'awards',
      date: 'Nov 15, 2024',
      location: 'Barry',
      author: 'Quality Team',
      badge: '',
      views: 892,
      likes: 67,
      shares: 34,
      comments: 8,
      readTime: '3 min read'
    },
    {
      id: 'health-tech',
      title: 'New Health Monitoring Technology',
      excerpt: 'Advanced wearable devices now monitor resident health 24/7, providing real-time alerts and improved care coordination.',
      image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
      category: 'innovation',
      date: 'Oct 28, 2024',
      location: 'All Locations',
      author: 'Technology Team',
      badge: '',
      views: 1567,
      likes: 89,
      shares: 45,
      comments: 15,
      readTime: '4 min read'
    },
    {
      id: 'community-garden',
      title: 'Therapeutic Garden Project Launch',
      excerpt: 'Residents at Cardiff Bay home celebrate the opening of new sensory gardens designed for therapeutic activities and relaxation.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
      category: 'community',
      date: 'Sep 12, 2024',
      location: 'Cardiff',
      author: 'Wellness Team',
      badge: '',
      views: 743,
      likes: 52,
      shares: 28,
      comments: 9,
      readTime: '3 min read'
    }
  ];
